// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_1_1perfilesPage from "./routes/1_1perfilesPage.tsx";
import * as $_1_2filtrarPage from "./routes/1_2filtrarPage.tsx";
import * as $_2_1addPage from "./routes/2_1addPage.tsx";
import * as $_2_2perfilPage from "./routes/2_2perfilPage.tsx";
import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $deletePage from "./routes/deletePage.tsx";
import * as $index from "./routes/index.tsx";
import * as $AddManager from "./islands/AddManager.tsx";
import * as $DeleteManager from "./islands/DeleteManager.tsx";
import * as $FilterManager from "./islands/FilterManager.tsx";
import * as $LoginManager from "./islands/LoginManager.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/1_1perfilesPage.tsx": $_1_1perfilesPage,
    "./routes/1_2filtrarPage.tsx": $_1_2filtrarPage,
    "./routes/2_1addPage.tsx": $_2_1addPage,
    "./routes/2_2perfilPage.tsx": $_2_2perfilPage,
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/deletePage.tsx": $deletePage,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AddManager.tsx": $AddManager,
    "./islands/DeleteManager.tsx": $DeleteManager,
    "./islands/FilterManager.tsx": $FilterManager,
    "./islands/LoginManager.tsx": $LoginManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
